### ISSUE TITLE
Feature Request: Add FuseSoC support

### ISSUE THREAD

**Issue by mithro** [lewiz-support/LMAC_CORE1#2]
It would be awesome for this core to support [FuseSoC](https://github.com/olofk/fusesoc).
>FuseSoC is an award-winning package manager and a set of build tools for HDL (Hardware Description Language) code.
>
>Its main purpose is to increase reuse of IP (Intellectual Property) cores and be an aid for creating, building and simulating SoC solutions.

@olofk can give you advice on how to do this

**Comment by olofk** [comment]
Happy to help out. I believe the first step would be to add a core description file that easily allows this core to be integrated in other designs. The next step would be to run the regression tests with FuseSoC as well, but looking at the current structure that would likely benefit from a couple of changes to the test infrastructure to more easily allow other simulators to be used as well

**Comment by lewiz-support** [comment]
We currently don't have plan to do this for FuseSoC. We welcome contributions from the community.
