### ISSUE TITLE
Feature Request: Example of deployment on an FPGA board

### ISSUE THREAD

**Issue by mithro** [lewiz-support/LMAC_CORE1#4]
An example which shows how to use the core on an FPGA board that I can purchase would be awesome. Some boards which would be awesome to support are;
 * https://store.digilentinc.com/nexys-video-artix-7-fpga-trainer-board-for-multimedia-applications/
 * https://store.digilentinc.com/genesys-2-kintex-7-fpga-development-board/

**Comment by lewiz-support** [comment]
We plan to release FPGA support for the core in 2020 for 1 or 2 reference boards.
We welcome contributions from the community.
