### ISSUE TITLE
reg_rd_done has multiple drivers

### ISSUE THREAD

**Issue by olofk** [lewiz-support/LMAC_CORE1#5]
reg_rd_done in LMAC_CORE_TOP has multiple drivers coming from different clock domains

**Comment by lewiz-support** [comment]
We will take a look at this.

**Comment by lewiz-support** [comment]
Line 285 of previous release should have been commented out to avoid driving by multiple always loop.
We removed it (now line 286) from LMAC_CORE_TOP.v 
This should fix your issue. Thank you for letting us know.
