### ISSUE TITLE
Questions about the GMII interface from LMAC_CORE_TOP

### ISSUE THREAD

**Issue by Yuan-Mao** [lewiz-support/LMAC_CORE1#6]
Hi, thank you for this open-source Ethernet Core Repo!

I have two questions about the GMII interface from LMAC_CORE_TOP.v.

1. For TX, to my understanding, the GMII interface usually has TX_ER signal, but it seems to me there's no signal related to it and I can only be able to find gmii_tx_vld, which I think does not belong to the standard TX GMII interface (TXD, TXC, TX_EN, TX_ER). Does gmii_tx_vld is actually the TX_ER signal?

2. For RX, the GMII interface from LMAC_CORE_TOP does not include RX_ER. This should be part of the GMII standard as well. Not sure if I have missed something or there's actually a reason to skip the RX_ER signal in LMAC_CORE_TOP?

Thank you very much!

**Comment by taylor-bsg** [comment]
@lewiz-support any help with this? Thanks!

**Comment by lewiz-support** [comment]
Just saw your issue. We will have someone look into this

**Comment by lewiz-support** [comment]
TX_ER: The LMAC Core does not transmit erroneous packet. so it has no use for TX_ER.
TX_VLD: this is more like TX_EN
RX_ER: This is PHY dependent. These days it does not seem this is very useful. Can you provide some conditions that you would need to assert this from the PHY? The LMAC can accept full packets. It also looks for bad frames and does not depend on the PHY to do this.

**Comment by Yuan-Mao** [comment]
I see. Thanks for the clarification!

I was looking at this [FMC module](https://www.avnet.com/shop/us/products/avnet-engineering-services/aes-fmc-netw1-g-3074457345635205181/) (By the way this is RGMII interface instead of GMII). The core chip on that module has RGMII RX_CTL signal(which includes RX_ER), but I just realized the error signal has been combined with enable signal within the FMC module, so from the user perspective there is actually no RX_ER to connect.

Also one more question, do you provide GMII-RGMII converter in this repo? Thank you!

**Comment by Yuan-Mao** [comment]
Could you please elaborate more on the difference between gmii_tx_en and gmii_tx_vld? The [external PHY chip](https://www.avnet.com/shop/us/products/avnet-engineering-services/aes-fmc-netw1-g-3074457345635205181/) I'm looking at only has tx_en. Which do you think I should connect?

Thanks!

**Comment by lewiz-support** [comment]
We think it’s tx_dvld

But have not seen the spec of the PHY chip on that board.

Do you have a spec of the PHY chip they used on that board?

**Comment by Yuan-Mao** [comment]
Hi, this is the RGMII PHY chip I will be using: https://ww1.microchip.com/downloads/en/DeviceDoc/00002117G.pdf
If it is tx_vld, then when will we use tx_en?

**Comment by lewiz-support** [comment]
We provide different signals because different PHY (internal vs. external) has different set of signals.

In this case, just tie tx_en = 1
