### ISSUE TITLE
gmii_rx_dv is not used in LMAC_CORE_TOP module

### ISSUE THREAD

**Issue by Yuan-Mao** [lewiz-support/LMAC_CORE1#8]
Hi,

It seems to me that gmii_rx_dv is not used in LMAC_CORE_TOP module.

The following is my code trace:

LMAC_CORE_TOP(gmii_rx_dv) -> gige_rx(gmii_rx_dv) -> gige_s2p(gmii_rx_dv) -> END

Thanks!

**Comment by lewiz-support** [comment]
the RX side uses gmii_rxc instead. It has the same function as gmii_rx_dv. Connect your gmii control signal from the PHY to gmii_rxc
