### ISSUE TITLE
Question about gmii_rxc in LMAC_CORE_TOP

### ISSUE THREAD

**Issue by Yuan-Mao** [lewiz-support/LMAC_CORE1#9]
Hi,

I'm not sure if gmii_rxc is the clock source from the external PHY? If it is, then I'm not sure why gmii_rxc is used as data signal inside gige_s2p. Also, according to the code in gige_s2p,  the gmii_rxc seems to be synchronous to the FMAC clock (125 MHZ). To my understanding, the FMAC clock source should be different from gmii_rxc, which comes from the external PHY.

Thanks!

**Comment by lewiz-support** [comment]
gmii_rxc is the control signal (similar to a data valid indicator). It essentially is the control of gmii_rxd.
